// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bandicoot.proto
// Protobuf C++ Version: 5.29.3

#include "bandicoot.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace bandicoot {
              template <typename>
PROTOBUF_CONSTEXPR Void::Void(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct VoidDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VoidDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VoidDefaultTypeInternal() {}
  union {
    Void _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VoidDefaultTypeInternal _Void_default_instance_;

inline constexpr TestMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : first_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        second_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TestMsg::TestMsg(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct TestMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TestMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestMsgDefaultTypeInternal() {}
  union {
    TestMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestMsgDefaultTypeInternal _TestMsg_default_instance_;
}  // namespace bandicoot
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_bandicoot_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_bandicoot_2eproto = nullptr;
const ::uint32_t
    TableStruct_bandicoot_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::bandicoot::TestMsg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::bandicoot::TestMsg, _impl_.first_),
        PROTOBUF_FIELD_OFFSET(::bandicoot::TestMsg, _impl_.second_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::bandicoot::Void, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::bandicoot::TestMsg)},
        {10, -1, -1, sizeof(::bandicoot::Void)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::bandicoot::_TestMsg_default_instance_._instance,
    &::bandicoot::_Void_default_instance_._instance,
};
const char descriptor_table_protodef_bandicoot_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017bandicoot.proto\022\tbandicoot\"(\n\007TestMsg\022"
    "\r\n\005first\030\001 \001(\t\022\016\n\006second\030\002 \001(\t\"\006\n\004Void2F"
    "\n\nDesktopApp\0228\n\021OnSanitizerReport\022\022.band"
    "icoot.TestMsg\032\017.bandicoot.Voidb\006proto3"
};
static ::absl::once_flag descriptor_table_bandicoot_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_bandicoot_2eproto = {
    false,
    false,
    158,
    descriptor_table_protodef_bandicoot_2eproto,
    "bandicoot.proto",
    &descriptor_table_bandicoot_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_bandicoot_2eproto::offsets,
    file_level_enum_descriptors_bandicoot_2eproto,
    file_level_service_descriptors_bandicoot_2eproto,
};
namespace bandicoot {
// ===================================================================

class TestMsg::_Internal {
 public:
};

TestMsg::TestMsg(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:bandicoot.TestMsg)
}
inline PROTOBUF_NDEBUG_INLINE TestMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::bandicoot::TestMsg& from_msg)
      : first_(arena, from.first_),
        second_(arena, from.second_),
        _cached_size_{0} {}

TestMsg::TestMsg(
    ::google::protobuf::Arena* arena,
    const TestMsg& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  TestMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:bandicoot.TestMsg)
}
inline PROTOBUF_NDEBUG_INLINE TestMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : first_(arena),
        second_(arena),
        _cached_size_{0} {}

inline void TestMsg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
TestMsg::~TestMsg() {
  // @@protoc_insertion_point(destructor:bandicoot.TestMsg)
  SharedDtor(*this);
}
inline void TestMsg::SharedDtor(MessageLite& self) {
  TestMsg& this_ = static_cast<TestMsg&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.first_.Destroy();
  this_._impl_.second_.Destroy();
  this_._impl_.~Impl_();
}

inline void* TestMsg::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) TestMsg(arena);
}
constexpr auto TestMsg::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(TestMsg),
                                            alignof(TestMsg));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull TestMsg::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_TestMsg_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &TestMsg::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<TestMsg>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &TestMsg::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<TestMsg>(), &TestMsg::ByteSizeLong,
            &TestMsg::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(TestMsg, _impl_._cached_size_),
        false,
    },
    &TestMsg::kDescriptorMethods,
    &descriptor_table_bandicoot_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* TestMsg::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 37, 2> TestMsg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::bandicoot::TestMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string second = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.second_)}},
    // string first = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.first_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string first = 1;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.first_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string second = 2;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.second_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\5\6\0\0\0\0\0"
    "bandicoot.TestMsg"
    "first"
    "second"
  }},
};

PROTOBUF_NOINLINE void TestMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:bandicoot.TestMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.first_.ClearToEmpty();
  _impl_.second_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* TestMsg::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const TestMsg& this_ = static_cast<const TestMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* TestMsg::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const TestMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:bandicoot.TestMsg)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string first = 1;
          if (!this_._internal_first().empty()) {
            const std::string& _s = this_._internal_first();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "bandicoot.TestMsg.first");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string second = 2;
          if (!this_._internal_second().empty()) {
            const std::string& _s = this_._internal_second();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "bandicoot.TestMsg.second");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:bandicoot.TestMsg)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t TestMsg::ByteSizeLong(const MessageLite& base) {
          const TestMsg& this_ = static_cast<const TestMsg&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t TestMsg::ByteSizeLong() const {
          const TestMsg& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:bandicoot.TestMsg)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string first = 1;
            if (!this_._internal_first().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_first());
            }
            // string second = 2;
            if (!this_._internal_second().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_second());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void TestMsg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TestMsg*>(&to_msg);
  auto& from = static_cast<const TestMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:bandicoot.TestMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_first().empty()) {
    _this->_internal_set_first(from._internal_first());
  }
  if (!from._internal_second().empty()) {
    _this->_internal_set_second(from._internal_second());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TestMsg::CopyFrom(const TestMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bandicoot.TestMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TestMsg::InternalSwap(TestMsg* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.first_, &other->_impl_.first_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.second_, &other->_impl_.second_, arena);
}

::google::protobuf::Metadata TestMsg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Void::_Internal {
 public:
};

Void::Void(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:bandicoot.Void)
}
Void::Void(
    ::google::protobuf::Arena* arena,
    const Void& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Void* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:bandicoot.Void)
}

inline void* Void::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Void(arena);
}
constexpr auto Void::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Void),
                                            alignof(Void));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Void::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Void_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Void::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<Void>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Void::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<Void>(), &Void::ByteSizeLong,
            &Void::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Void, _impl_._cached_size_),
        false,
    },
    &Void::kDescriptorMethods,
    &descriptor_table_bandicoot_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Void::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> Void::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::bandicoot::Void>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata Void::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace bandicoot
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_bandicoot_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
