// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: bandicoot.proto
#ifndef GRPC_bandicoot_2eproto__INCLUDED
#define GRPC_bandicoot_2eproto__INCLUDED

#include "bandicoot.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace bandicoot {

class DesktopApp final {
 public:
  static constexpr char const* service_full_name() {
    return "bandicoot.DesktopApp";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status OnSanitizerReport(::grpc::ClientContext* context, const ::bandicoot::TsanReport& request, ::bandicoot::Void* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bandicoot::Void>> AsyncOnSanitizerReport(::grpc::ClientContext* context, const ::bandicoot::TsanReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bandicoot::Void>>(AsyncOnSanitizerReportRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bandicoot::Void>> PrepareAsyncOnSanitizerReport(::grpc::ClientContext* context, const ::bandicoot::TsanReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::bandicoot::Void>>(PrepareAsyncOnSanitizerReportRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void OnSanitizerReport(::grpc::ClientContext* context, const ::bandicoot::TsanReport* request, ::bandicoot::Void* response, std::function<void(::grpc::Status)>) = 0;
      virtual void OnSanitizerReport(::grpc::ClientContext* context, const ::bandicoot::TsanReport* request, ::bandicoot::Void* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bandicoot::Void>* AsyncOnSanitizerReportRaw(::grpc::ClientContext* context, const ::bandicoot::TsanReport& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::bandicoot::Void>* PrepareAsyncOnSanitizerReportRaw(::grpc::ClientContext* context, const ::bandicoot::TsanReport& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status OnSanitizerReport(::grpc::ClientContext* context, const ::bandicoot::TsanReport& request, ::bandicoot::Void* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bandicoot::Void>> AsyncOnSanitizerReport(::grpc::ClientContext* context, const ::bandicoot::TsanReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bandicoot::Void>>(AsyncOnSanitizerReportRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bandicoot::Void>> PrepareAsyncOnSanitizerReport(::grpc::ClientContext* context, const ::bandicoot::TsanReport& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::bandicoot::Void>>(PrepareAsyncOnSanitizerReportRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void OnSanitizerReport(::grpc::ClientContext* context, const ::bandicoot::TsanReport* request, ::bandicoot::Void* response, std::function<void(::grpc::Status)>) override;
      void OnSanitizerReport(::grpc::ClientContext* context, const ::bandicoot::TsanReport* request, ::bandicoot::Void* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::bandicoot::Void>* AsyncOnSanitizerReportRaw(::grpc::ClientContext* context, const ::bandicoot::TsanReport& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::bandicoot::Void>* PrepareAsyncOnSanitizerReportRaw(::grpc::ClientContext* context, const ::bandicoot::TsanReport& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_OnSanitizerReport_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status OnSanitizerReport(::grpc::ServerContext* context, const ::bandicoot::TsanReport* request, ::bandicoot::Void* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_OnSanitizerReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OnSanitizerReport() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_OnSanitizerReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSanitizerReport(::grpc::ServerContext* /*context*/, const ::bandicoot::TsanReport* /*request*/, ::bandicoot::Void* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnSanitizerReport(::grpc::ServerContext* context, ::bandicoot::TsanReport* request, ::grpc::ServerAsyncResponseWriter< ::bandicoot::Void>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_OnSanitizerReport<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_OnSanitizerReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OnSanitizerReport() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::bandicoot::TsanReport, ::bandicoot::Void>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::bandicoot::TsanReport* request, ::bandicoot::Void* response) { return this->OnSanitizerReport(context, request, response); }));}
    void SetMessageAllocatorFor_OnSanitizerReport(
        ::grpc::MessageAllocator< ::bandicoot::TsanReport, ::bandicoot::Void>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::bandicoot::TsanReport, ::bandicoot::Void>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_OnSanitizerReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSanitizerReport(::grpc::ServerContext* /*context*/, const ::bandicoot::TsanReport* /*request*/, ::bandicoot::Void* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OnSanitizerReport(
      ::grpc::CallbackServerContext* /*context*/, const ::bandicoot::TsanReport* /*request*/, ::bandicoot::Void* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_OnSanitizerReport<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_OnSanitizerReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OnSanitizerReport() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_OnSanitizerReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSanitizerReport(::grpc::ServerContext* /*context*/, const ::bandicoot::TsanReport* /*request*/, ::bandicoot::Void* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_OnSanitizerReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OnSanitizerReport() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_OnSanitizerReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSanitizerReport(::grpc::ServerContext* /*context*/, const ::bandicoot::TsanReport* /*request*/, ::bandicoot::Void* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnSanitizerReport(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OnSanitizerReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OnSanitizerReport() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->OnSanitizerReport(context, request, response); }));
    }
    ~WithRawCallbackMethod_OnSanitizerReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnSanitizerReport(::grpc::ServerContext* /*context*/, const ::bandicoot::TsanReport* /*request*/, ::bandicoot::Void* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OnSanitizerReport(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_OnSanitizerReport : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_OnSanitizerReport() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::bandicoot::TsanReport, ::bandicoot::Void>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::bandicoot::TsanReport, ::bandicoot::Void>* streamer) {
                       return this->StreamedOnSanitizerReport(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_OnSanitizerReport() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OnSanitizerReport(::grpc::ServerContext* /*context*/, const ::bandicoot::TsanReport* /*request*/, ::bandicoot::Void* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedOnSanitizerReport(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::bandicoot::TsanReport,::bandicoot::Void>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_OnSanitizerReport<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_OnSanitizerReport<Service > StreamedService;
};

}  // namespace bandicoot


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_bandicoot_2eproto__INCLUDED
