// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: instruments2.proto

#include "instruments2.pb.h"
#include "instruments2.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace instruments2 {

static const char* DesktopApp_method_names[] = {
  "/instruments2.DesktopApp/OnSanitizerReport",
};

std::unique_ptr< DesktopApp::Stub> DesktopApp::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DesktopApp::Stub> stub(new DesktopApp::Stub(channel, options));
  return stub;
}

DesktopApp::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_OnSanitizerReport_(DesktopApp_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DesktopApp::Stub::OnSanitizerReport(::grpc::ClientContext* context, const ::instruments2::TsanReport& request, ::instruments2::Void* response) {
  return ::grpc::internal::BlockingUnaryCall< ::instruments2::TsanReport, ::instruments2::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OnSanitizerReport_, context, request, response);
}

void DesktopApp::Stub::async::OnSanitizerReport(::grpc::ClientContext* context, const ::instruments2::TsanReport* request, ::instruments2::Void* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::instruments2::TsanReport, ::instruments2::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OnSanitizerReport_, context, request, response, std::move(f));
}

void DesktopApp::Stub::async::OnSanitizerReport(::grpc::ClientContext* context, const ::instruments2::TsanReport* request, ::instruments2::Void* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OnSanitizerReport_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::instruments2::Void>* DesktopApp::Stub::PrepareAsyncOnSanitizerReportRaw(::grpc::ClientContext* context, const ::instruments2::TsanReport& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::instruments2::Void, ::instruments2::TsanReport, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OnSanitizerReport_, context, request);
}

::grpc::ClientAsyncResponseReader< ::instruments2::Void>* DesktopApp::Stub::AsyncOnSanitizerReportRaw(::grpc::ClientContext* context, const ::instruments2::TsanReport& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOnSanitizerReportRaw(context, request, cq);
  result->StartCall();
  return result;
}

DesktopApp::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DesktopApp_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DesktopApp::Service, ::instruments2::TsanReport, ::instruments2::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DesktopApp::Service* service,
             ::grpc::ServerContext* ctx,
             const ::instruments2::TsanReport* req,
             ::instruments2::Void* resp) {
               return service->OnSanitizerReport(ctx, req, resp);
             }, this)));
}

DesktopApp::Service::~Service() {
}

::grpc::Status DesktopApp::Service::OnSanitizerReport(::grpc::ServerContext* context, const ::instruments2::TsanReport* request, ::instruments2::Void* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace instruments2
#include <grpcpp/ports_undef.inc>

